"""Render catalog/metrics into paper artifacts (LaTeX tables, figures)."""

from .detector_rules import (
    BPF_FILTERS_FILENAME,
    DETECTOR_RULES_MARKDOWN_FILENAME,
    DETECTOR_RULES_SCHEMA_VERSION,
    IPTABLES_U32_RULES_FILENAME,
    NFTABLES_RULES_FILENAME,
    STATEFUL_PLAN_MARKDOWN_FILENAME,
    STATEFUL_SURICATA_FILENAME,
    STATEFUL_ZEEK_FILENAME,
    DetectorRuleArtifact,
    detector_rule_artifacts,
    detector_rule_manifest,
    detector_rules_markdown,
    stateful_detector_plan_markdown,
    suricata_stateful_detector_rules,
    write_detector_rule_artifacts,
    zeek_stateful_detector_script,
)
from .figures import (
    CAPACITY_BY_CLASS_FILENAME,
    CLASS_LAYER_HEATMAP_FILENAME,
    THROUGHPUT_UPPER_BOUNDS_FILENAME,
    ClassCapacitySummary,
    FigureArtifact,
    capacity_by_class_data,
    capacity_by_class_svg,
    catalog_figure_artifacts,
    class_layer_count_data,
    class_layer_heatmap_svg,
    write_catalog_figures,
)
from .guidance import detector_scrub_guidance_markdown
from .macros import (
    SurveyScaleMacros,
    count_wiki_pages,
    parse_cited_rfc_count,
    parse_rfc_corpus_swept_count,
    survey_scale_macros,
    survey_scale_macros_tex,
)
from .protocol_rates import (
    PROTOCOL_RATE_CLAIM_STATUS,
    ProtocolRate,
    ProtocolThroughputEstimate,
    load_protocol_rates,
    protocol_rates_markdown,
    throughput_estimates,
)
from .support_matrix import (
    SUPPORT_MATRIX_SCHEMA_VERSION,
    SupportMatrixReport,
    SupportMatrixRow,
    support_matrix_markdown,
    support_matrix_report,
)
from .tables import mechanisms_to_longtable
from .windows_capture import (
    MICROSOFT_PKTMON_DOCS,
    WINDOWS_CAPTURE_GUIDANCE_CLAIM_STATUS,
    WINDOWS_CAPTURE_GUIDANCE_FILENAME,
    windows_pktmon_guidance_markdown,
)

__all__ = [
    "BPF_FILTERS_FILENAME",
    "CAPACITY_BY_CLASS_FILENAME",
    "CLASS_LAYER_HEATMAP_FILENAME",
    "DETECTOR_RULES_MARKDOWN_FILENAME",
    "DETECTOR_RULES_SCHEMA_VERSION",
    "IPTABLES_U32_RULES_FILENAME",
    "MICROSOFT_PKTMON_DOCS",
    "NFTABLES_RULES_FILENAME",
    "PROTOCOL_RATE_CLAIM_STATUS",
    "STATEFUL_PLAN_MARKDOWN_FILENAME",
    "STATEFUL_SURICATA_FILENAME",
    "STATEFUL_ZEEK_FILENAME",
    "SUPPORT_MATRIX_SCHEMA_VERSION",
    "THROUGHPUT_UPPER_BOUNDS_FILENAME",
    "WINDOWS_CAPTURE_GUIDANCE_CLAIM_STATUS",
    "WINDOWS_CAPTURE_GUIDANCE_FILENAME",
    "ClassCapacitySummary",
    "DetectorRuleArtifact",
    "FigureArtifact",
    "ProtocolRate",
    "ProtocolThroughputEstimate",
    "SupportMatrixReport",
    "SupportMatrixRow",
    "SurveyScaleMacros",
    "capacity_by_class_data",
    "capacity_by_class_svg",
    "catalog_figure_artifacts",
    "class_layer_count_data",
    "class_layer_heatmap_svg",
    "count_wiki_pages",
    "detector_rule_artifacts",
    "detector_rule_manifest",
    "detector_rules_markdown",
    "detector_scrub_guidance_markdown",
    "load_protocol_rates",
    "mechanisms_to_longtable",
    "parse_cited_rfc_count",
    "parse_rfc_corpus_swept_count",
    "protocol_rates_markdown",
    "stateful_detector_plan_markdown",
    "support_matrix_markdown",
    "support_matrix_report",
    "suricata_stateful_detector_rules",
    "survey_scale_macros",
    "survey_scale_macros_tex",
    "throughput_estimates",
    "windows_pktmon_guidance_markdown",
    "write_catalog_figures",
    "write_detector_rule_artifacts",
    "zeek_stateful_detector_script",
]
