"""Generated detection views: emit packet-filter rules from located mechanisms,
and report honestly on what cannot be matched on the wire."""

from __future__ import annotations

from .replay import (
    DETECTOR_REPLAY_CORPUS_SCHEMA_VERSION,
    DETECTOR_REPLAY_SCHEMA_VERSION,
    DETECTOR_TRACE_MANIFEST_SCHEMA_VERSION,
    FALSE_POSITIVE_SOURCE_KINDS,
    DetectorReplayBackend,
    DetectorReplayCorpusReport,
    DetectorReplayMechanismResult,
    DetectorReplayReport,
    DetectorReplayTrace,
    DetectorReplayTraceSpec,
    DetectorReplayTraceSummary,
    TraceSourceKind,
    default_replay_mechanisms,
    load_trace_manifest,
    replay_detector_corpus,
    replay_detectors_on_pcap,
)
from .rules import (
    DetectorImplementationKind,
    DetectorProvenanceRecord,
    bpf_filter,
    classic_pcap_record_count,
    coverage,
    detector_provenance_for,
    emittable,
    iptables_u32_rule,
    nftables_rule,
    tcpdump_bpf_provenance_record,
)
from .scrub import (
    SCRUB_CLAIM_STATUS,
    SCRUB_REPORT_SCHEMA_VERSION,
    PcapScrubReport,
    ScrubArtifact,
    scrub_pcap,
    scrub_tcp_reserved_bits_pcap,
)
from .stateful import (
    STATEFUL_DETECTOR_CLAIM_STATUS,
    StatefulDetectorKind,
    StatefulDetectorPlan,
    stateful_detector_plan_for,
    stateful_detector_plans,
)

__all__ = [
    "DETECTOR_REPLAY_CORPUS_SCHEMA_VERSION",
    "DETECTOR_REPLAY_SCHEMA_VERSION",
    "DETECTOR_TRACE_MANIFEST_SCHEMA_VERSION",
    "FALSE_POSITIVE_SOURCE_KINDS",
    "SCRUB_CLAIM_STATUS",
    "SCRUB_REPORT_SCHEMA_VERSION",
    "STATEFUL_DETECTOR_CLAIM_STATUS",
    "DetectorImplementationKind",
    "DetectorProvenanceRecord",
    "DetectorReplayBackend",
    "DetectorReplayCorpusReport",
    "DetectorReplayMechanismResult",
    "DetectorReplayReport",
    "DetectorReplayTrace",
    "DetectorReplayTraceSpec",
    "DetectorReplayTraceSummary",
    "PcapScrubReport",
    "ScrubArtifact",
    "StatefulDetectorKind",
    "StatefulDetectorPlan",
    "TraceSourceKind",
    "bpf_filter",
    "classic_pcap_record_count",
    "coverage",
    "default_replay_mechanisms",
    "detector_provenance_for",
    "emittable",
    "iptables_u32_rule",
    "load_trace_manifest",
    "nftables_rule",
    "replay_detector_corpus",
    "replay_detectors_on_pcap",
    "scrub_pcap",
    "scrub_tcp_reserved_bits_pcap",
    "stateful_detector_plan_for",
    "stateful_detector_plans",
    "tcpdump_bpf_provenance_record",
]
